const Constant = {
  TENANT: "tenant",
  OWNER: "owner",

  AGREEMENT_ALL: 0,
  AGREEMENT_DRAFT: 1,
  AGREEMENT_PENDING: 2,
  AGREEMENT_COMPLETED: 3,

  UNPAID: "UNPAID",
  PAID: "PAID",

  INVOICE_OVER_DUE: "2",
  INVOICE_COMING_SOON: "1",
  INVOICE_PAID: "3",

  TENANCY: "Tenancy",
  POLICY: "Policy",

  HOME_FOR_RENT: "whole-unit",
  ROOM_FOR_RENT: "sublet",

  MAINTENANCE_REQUEST_VALUE: 1,
  GENERAL_ENQUIRIES_VALUE: 2,

  ENQUIRY: 1,
  FEEDBACK: 2,

  AMENITIES: 3,
  ELECTRICAL: 4,
  PLUMBING: 5,
  EXTERIOR_INTERIOR: 6,
  CLEANING: 7,

  SUGGESTION: 1,
  REVIEW: 2,
  COMPLAINT: 3,

  LOW: 1,
  NORMAL: 2,
  HIGH: 3,
  CRITICAL: 4,

  TICKET_NEW: 1,
  TICKET_PENDING: 2,
  TICKET_ON_HOLD: 3,
  TICKET_IN_PROGRESS: 4,
  TICKET_CLOSED: 5,
  TICKET_CANCELLED: 6,

  WALLET_EXPENSE: 1,
  WALLET_RENTAL_INCOME: 2,
  WALLET_WITHDRAWAL: 3,
  WALLET_INVOICE_PAYMENT: 4,
  WALLET_MANUAL_PAID_INVOICE_REVERT_PAYMENT: 5,
  WALLET_WITHDRAWAL_REFUND: 6,
  WALLET_REVERT_INVOICE_PAYMENT: 7,

  WALLET_WITHDRAW_PENDING: 1,
  WALLET_WITHDRAW_CONFIRM: 2,
  WALLET_WITHDRAW_APPROVED: 3,
  WALLET_WITHDRAW_CANCELLED: 4,
};

export default Constant;
