const Constant = {
  TENANT: "Tenant",
  OWNER: "Owner",

  AGREEMENT_ALL: 0,
  AGREEMENT_DRAFT: 1,
  AGREEMENT_PENDING: 2,
  AGREEMENT_COMPLETED: 3,

  UNPAID: "UNPAID",
  PAID: "PAID",

  INVOICE_OVER_DUE: "2",
  INVOICE_COMING_SOON: "1",
  INVOICE_PAID: "3",

  TENANCY: "Tenancy",
  POLICY: "Policy",

  HOME_FOR_RENT: "whole-unit",
  ROOM_FOR_RENT: "sublet",

  MAINTENANCE_REQUESTS: "Maintenance Requests",
  GENERAL_ENQUIRIES: "General Enquiries Requests",

  ENQUIRY: "Enquiry",
  FEEDBACK: "Feedback",

  AMENITIES: "Amenities",
  ELECTRICAL: "Electrical",
  PLUMBING: "Plumbing",
  EXTERIOR_INTERIOR: "Exterior&Interior",
  CLEANING: "Cleaning",

  WALLET_EXPENSE: 1,
  WALLET_RENTAL_INCOME: 2,
  WALLET_WITHDRAWAL: 3,
  WALLET_INVOICE_PAYMENT: 4,
  WALLET_MANUAL_PAID_INVOICE_REVERT_PAYMENT: 5,
  WALLET_WITHDRAWAL_REFUND: 6,
  WALLET_REVERT_INVOICE_PAYMENT: 7,

  WALLET_WITHDRAW_PENDING: 1,
  WALLET_WITHDRAW_CONFIRM: 2,
  WALLET_WITHDRAW_APPROVED: 3,
  WALLET_WITHDRAW_CANCELLED: 4,
};

export default Constant;
