const Image = {
  searchIcon: "/images/icon/search_icon.png",
  searchIconActive: "/images/icon/search_icon_active.png",
  homeIcon: "/images/icon/home_icon.png",
  homeIconActive: "/images/icon/home_icon_active.png",
  accountIcon: "/images/icon/account_icon.png",
  accountIconActive: "/images/icon/account_icon_active.png",
  leftIcon: "/images/icon/left_icon.png",
  rightIcon: "/images/icon/right_icon.png",
  userIcon: "/images/icon/user_icon.png",
  phoneIcon: "/images/icon/phone_icon.png",
  emailIcon: "/images/icon/email_icon.png",
  refreshIcon: "/images/icon/refresh_icon.png",
  buildingIcon: "/images/icon/building_icon.png",
  qrIcon: "/images/icon/qr_icon.png",
  lockIcon: "/images/icon/lock_icon.png",
  helpIcon: "/images/icon/help_icon.png",
  agreementIcon: "/images/icon/agreement_icon.png",
  meterIcon: "/images/icon/meter_icon.png",
  onIcon: "/images/icon/on_icon.png",
  offIcon: "/images/icon/off_icon.png",
  moreIcon: "/images/icon/more_icon.png",
  invoiceIcon: "/images/icon/invoice_icon.png",
  editIcon: "/images/icon/edit_icon.png",
  primaryInvoiceIcon: "/images/icon/primary_invoice_icon.png",
  primaryLockIcon: "/images/icon/primary_lock.png",
  primaryLogoutIcon: "/images/icon/primary_logout_icon.png",
  primaryMeterIcon: "/images/icon/primary_meter.png",
  primaryRingIcon: "/images/icon/primary_ring_icon.png",
  primaryTermAndConditionIcon:
    "/images/icon/primary_term_and_condition_icon.png",
  inactiveCheckIcon: "/images/icon/inactive_check_icon.png",
  downIcon: "/images/icon/down_icon.png",
  filterIcon: "/images/icon/filter_icon.png",
  searchOutlineActiveIcon: "/images/icon/search_outline_active_icon.png",
  topBackgroundImage: "/images/top_background.png",
  emptyImage: "/images/emptyBox.png",
  logoImage: "/images/logo.png",
  banner1Image: "/images/banner_1.png",
  banner2Image: "/images/banner_2.png",
  banner3Image: "/images/banner_3.png",
  listingDefaultImage: "/images/listing_default_image.png",
  filterDefaultImage: "/images/filter_default_image.png",
  unitAmenitiesIcon: "/images/amenities/unit_icon.png",
  bedAmenitiesIcon: "/images/amenities/bed_icon.png",
  windowAmenitiesIcon: "/images/amenities/window_icon.png",
  femaleAmenitiesIcon: "/images/amenities/female_icon.png",
  bathAmenitiesIcon: "/images/amenities/bath_icon.png",
  aircornAmenitiesIcon: "/images/amenities/aircorn_icon.png",
  wifiAmenitiesIcon: "/images/amenities/wifi_icon.png",
  laundryAmenitiesIcon: "/images/amenities/laundry_icon.png",
  cookAmenitiesIcon: "/images/amenities/cook_icon.png",
  swimmingAmenitiesIcon: "/images/amenities/swimming_icon.png",
  gymAmenitiesIcon: "/images/amenities/gym_icon.png",
  topUpIcon:"/images/icon/topUp_icon.png",
  clearIcon:"/images/icon/clear_icon.png",
  usageIcon:"/images/icon/usage_icon.png",
  disconnect:"/images/icon/disconnect_icon.png"
};

export default Image;
