const Image = {
  searchIcon: "/images/icon/search_icon.png",
  searchIconActive: "/images/icon/search_icon_active.png",
  homeIcon: "/images/icon/home_icon.png",
  homeIconActive: "/images/icon/home_icon_active.png",
  accountIcon: "/images/icon/account_icon.png",
  accountIconActive: "/images/icon/account_icon_active.png",
  leftIcon: "images/icon/left_icon.png",
  rightIcon: "images/icon/right_icon.png",
  userIcon: "images/icon/user_icon.png",
  phoneIcon: "images/icon/phone_icon.png",
  emailIcon: "images/icon/email_icon.png",
  refreshIcon: "images/icon/refresh_icon.png",
  buildingIcon: "images/icon/building_icon.png",
  qrIcon: "images/icon/qr_icon.png",
  lockIcon: "images/icon/lock_icon.png",
  helpIcon: "images/icon/help_icon.png",
  agreementIcon: "images/icon/agreement_icon.png",
  meterIcon: "images/icon/meter_icon.png",
  onIcon: "images/icon/on_icon.png",
  offIcon: "images/icon/off_icon.png",
  moreIcon: "images/icon/more_icon.png",
  invoiceIcon: "images/icon/invoice_icon.png",
  editIcon: "images/icon/edit_icon.png",
  primaryInvoiceIcon: "images/icon/primary_invoice_icon.png",
  primaryLockIcon: "images/icon/primary_lock.png",
  primaryLogoutIcon: "images/icon/primary_logout_icon.png",
  primaryMeterIcon: "images/icon/primary_meter.png",
  primaryRingIcon: "images/icon/primary_ring_icon.png",
  primaryTermAndConditionIcon: "images/icon/primary_term_and_condition_icon.png",
  inactiveCheckIcon: "images/icon/inactive_check_icon.png",
  topBackgroundImage: "/images/top_background.png",
  emptyImage: "/images/emptyBox.png",
  logoImage: "/images/logo.png",
};

export default Image;
