const GeneralImage = {
  accountIconFillBlack: "/images/general_icon/accounr_icon_fill_black.png",
  accountIconFillDisable: "/images/general_icon/accounr_icon_fill_disable.png",
  accountIconFillWhite: "/images/general_icon/accounr_icon_fill_white.png",
  accountIconBlack: "/images/general_icon/account_icon_black.png",
  accountIconDisable: "/images/general_icon/account_icon_disable.png",
  accountIconWhite: "/images/general_icon/account_icon_white.png",
  addIconBlack: "/images/general_icon/add_icon_black.png",
  addIconDisable: "/images/general_icon/add_icon_disable.png",
  addIconWhite: "/images/general_icon/add_icon_white.png",
  agreementIconBlack: "/images/general_icon/agreement_icon_black.png",
  agreementIconDisable: "/images/general_icon/agreement_icon_disable.png",
  agreementIconWhite: "/images/general_icon/agreement_icon_white.png",
  alertIconBlack: "/images/general_icon/alert_icon_black.png",
  alertIconDisable: "/images/general_icon/alert_icon_disable.png",
  alertIconWhite: "/images/general_icon/alert_icon_white.png",
  appointmentIconBlack: "/images/general_icon/appointment_icon_black.png",
  appointmentIconDisable: "/images/general_icon/appointment_icon_disable.png",
  appointmentIconWhite: "/images/general_icon/appointment_icon_white.png",
  bankIconBlack: "/images/general_icon/bank_icon_black.png",
  bankIconDisable: "/images/general_icon/bank_icon_disable.png",
  bankIconWhite: "/images/general_icon/bank_icon_white.png",
  bathroomIconBlack: "/images/general_icon/bathroom_icon_black.png",
  bathroomIconDisable: "/images/general_icon/bathroom_icon_disable.png",
  bathroomIconWhite: "/images/general_icon/bathroom_icon_white.png",
  bedIconBlack: "/images/general_icon/bed_icon_black.png",
  bedIconDisable: "/images/general_icon/bed_icon_disable.png",
  bedIconWhite: "/images/general_icon/bed_icon_white.png",
  beliveWhatsappIcon: "/images/general_icon/belive_whatsapp_icon.png",
  bnIcon: "/images/general_icon/bn_icon.png",
  bookmarkIconFill: "/images/general_icon/bookmark_icon_fill.png",
  bookmarkIcon: "/images/general_icon/bookmark_icon.png",
  buildingIconBlack: "/images/general_icon/building_icon_black.png",
  buildingIconDisable: "/images/general_icon/building_icon_disable.png",
  buildingIconWhite: "/images/general_icon/building_icon_white.png",
  calenderIconBlack: "/images/general_icon/calender_icon_black.png",
  carAvailableIcon: "/images/general_icon/car_available_icon.png",
  carDisableIcon: "/images/general_icon/car_disable_icon.png",
  carOccupiedIcon: "/images/general_icon/car_occupied_icon.png",
  carParkIconBlack: "/images/general_icon/car_park_icon_black.png",
  carParkIconDisable: "/images/general_icon/car_park_icon_disable.png",
  carParkIconWhite: "/images/general_icon/car_park_icon_white.png",
  carParkOccupancyIconBlack:
    "/images/general_icon/car_park_occupancy_icon_black.png",
  carParkOccupancyIconDisable:
    "/images/general_icon/car_park_occupancy_icon_disable.png",
  carParkOccupancyIconWhite:
    "/images/general_icon/car_park_occupancy_icon_white.png",
  chartIconBlack: "/images/general_icon/chart_icon_black.png",
  chartIconDisable: "/images/general_icon/chart_icon_disable.png",
  chartIconWhite: "/images/general_icon/chart_icon_white.png",
  chatIconBlack: "/images/general_icon/chat_icon_black.png",
  chatIconDisable: "/images/general_icon/chat_icon_disable.png",
  chatIconWhite: "/images/general_icon/chat_icon_white.png",
  checkIconAqua: "/images/general_icon/check_icon_aqua.png",
  checkIconBlack: "/images/general_icon/check_icon_black.png",
  checkIconDisable: "/images/general_icon/check_icon_disable.png",
  checkIconWhite: "/images/general_icon/check_icon_white.png",
  uncheckIconWhite: "/images/general_icon/uncheck_icon_white.png",
  circleIconActive: "/images/general_icon/circle_icon_active.png",
  circleIconAqua: "/images/general_icon/circle_icon_aqua.png",
  circleIconFillBlack: "/images/general_icon/circle_icon_fill_black.png",
  circleIconFillDisable: "/images/general_icon/circle_icon_fill_disable.png",
  circleIconFillWhite: "/images/general_icon/circle_icon_fill_white.png",
  cleaningIconBlack: "/images/general_icon/cleaning_icon_black.png",
  cleaningIconDisable: "/images/general_icon/cleaning_icon_disable.png",
  cleaningIconWhite: "/images/general_icon/cleaning_icon_white.png",
  clockIconBlack: "/images/general_icon/clock_icon_black.png",
  closeIconBlack: "/images/general_icon/close_icon_black.png",
  closeIconDisable: "/images/general_icon/close_icon_disable.png",
  closeIconWhite: "/images/general_icon/close_icon_white.png",
  coinIconBlack: "/images/general_icon/coin_icon_black.png",
  coinIconDisable: "/images/general_icon/coin_icon_disable.png",
  coinIconWhite: "/images/general_icon/coin_icon_white.png",
  deleteIcon: "/images/general_icon/delete_icon.png",
  downIconBlack: "/images/general_icon/down_icon_black.png",
  downIconDisable: "/images/general_icon/down_icon_disable.png",
  downIconWhite: "/images/general_icon/down_icon_white.png",
  downloadIconBlack: "/images/general_icon/download_icon_black.png",
  downloadIconDisable: "/images/general_icon/download_icon_disable.png",
  downloadIconWhite: "/images/general_icon/download_icon_white.png",
  editIconBlack: "/images/general_icon/edit_icon_black.png",
  editIconDisable: "/images/general_icon/edit_icon_disable.png",
  editIconWhite: "/images/general_icon/edit_icon_white.png",
  electricalIconBlack: "/images/general_icon/electrical_icon_black.png",
  electricalIconDisable: "/images/general_icon/electrical_icon_disable.png",
  electricalIconWhite: "/images/general_icon/electrical_icon_white.png",
  emailIconBlack: "/images/general_icon/email_icon_black.png",
  emailIconDisable: "/images/general_icon/email_icon_disable.png",
  emailIconWhite: "/images/general_icon/email_icon_white.png",
  enIcon: "/images/general_icon/en_icon.png",
  enquiryIconBlack: "/images/general_icon/enquiry_icon_black.png",
  enquiryIconDisable: "/images/general_icon/enquiry_icon_disable.png",
  enquiryIconWhite: "/images/general_icon/enquiry_icon_white.png",
  expensesIconBlack: "/images/general_icon/expenses_icon_black.png",
  expensesIconDisable: "/images/general_icon/expenses_icon_disable.png",
  expensesIconWhite: "/images/general_icon/expenses_icon_white.png",
  facebookIcon: "/images/general_icon/Facebook_icon.png",
  feedbackIconBlack: "/images/general_icon/feedback_icon_black.png",
  feedbackIconDisable: "/images/general_icon/feedback_icon_disable.png",
  feedbackIconWhite: "/images/general_icon/feedback_icon_white.png",
  filterIconBlack: "/images/general_icon/filter_icon_black.png",
  filterIconDisable: "/images/general_icon/filter_icon_disable.png",
  filterIconWhite: "/images/general_icon/filter_icon_white.png",
  generalEnquiryIconBlack:
    "/images/general_icon/general_enquiry_icon_black.png",
  generalEnquiryIconDisable:
    "/images/general_icon/general_enquiry_icon_disable.png",
  generalEnquiryIconWhite:
    "/images/general_icon/general_enquiry_icon_white.png",
  helpCenterIconBlack: "/images/general_icon/help_center_icon_black.png",
  helpCenterIconDisable: "/images/general_icon/help_center_icon_disable.png",
  helpCenterIconWhite: "/images/general_icon/help_center_icon_white.png",
  homeIconBlack: "/images/general_icon/home_icon_black.png",
  homeIconDisable: "/images/general_icon/home_icon_disable.png",
  homeIconFillBlack: "/images/general_icon/home_icon_fill_black.png",
  homeIconFillDisable: "/images/general_icon/home_icon_fill_disable.png",
  homeIconFillWhite: "/images/general_icon/home_icon_fill_white.png",
  homeIconWhite: "/images/general_icon/home_icon_white.png",
  imageIconBlack: "/images/general_icon/image_icon_black.png",
  imageIconDisable: "/images/general_icon/image_icon_disable.png",
  imageIconWhite: "/images/general_icon/image_icon_white.png",
  incomeIconBlack: "/images/general_icon/income_icon_black.png",
  incomeIconDisable: "/images/general_icon/income_icon_disable.png",
  incomeIconWhite: "/images/general_icon/income_icon_white.png",
  infoIconBlack: "/images/general_icon/info_icon_black.png",
  infoIconDisable: "/images/general_icon/info_icon_disable.png",
  infoIconWhite: "/images/general_icon/info_icon_white.png",
  instagramIcon: "/images/general_icon/Instagram_icon.png",
  invoiceIconBlack: "/images/general_icon/invoice_icon_black.png",
  invoiceIconDisable: "/images/general_icon/invoice_icon_disable.png",
  invoiceIconWhite: "/images/general_icon/invoice_icon_white.png",
  klccIcon: "/images/general_icon/klcc_icon.png",
  leftIconBlack: "/images/general_icon/left_icon_black.png",
  leftIconDisable: "/images/general_icon/left_icon_disable.png",
  leftIconWhite: "/images/general_icon/left_icon_white.png",
  linkinIcon: "/images/general_icon/linkin_icon.png",
  listIconBlack: "/images/general_icon/list_icon_black.png",
  listIconDisable: "/images/general_icon/list_icon_disable.png",
  listIconWhite: "/images/general_icon/list_icon_white.png",
  lockIconBlack: "/images/general_icon/lock_icon_black.png",
  lockIconDisable: "/images/general_icon/lock_icon_disable.png",
  lockIconWhite: "/images/general_icon/lock_icon_white.png",
  maintenanceRequestIconBlack:
    "/images/general_icon/maintenance_request_icon_black.png",
  maintenanceRequestIconDisable:
    "/images/general_icon/maintenance_request_icon_disable.png",
  maintenanceRequestIconWhite:
    "/images/general_icon/maintenance_request_icon_white.png",
  meterIconBlack: "/images/general_icon/meter_icon_black.png",
  meterIconDisable: "/images/general_icon/meter_icon_disable.png",
  meterIconWhite: "/images/general_icon/meter_icon_white.png",
  moreIconBlack: "/images/general_icon/more_icon_black.png",
  moreIconDisable: "/images/general_icon/more_icon_disable.png",
  moreIconWhite: "/images/general_icon/more_icon_white.png",
  occupancyIconBlack: "/images/general_icon/occupancy_icon_black.png",
  occupancyIconDisable: "/images/general_icon/occupancy_icon_disable.png",
  occupancyIconWhite: "/images/general_icon/occupancy_icon_white.png",
  paymentFailedIcon: "/images/general_icon/payment_failed_icon.png",
  paymentSuccessIcon: "/images/general_icon/payment_success_icon.png",
  percentIconBlack: "/images/general_icon/percent_icon_black.png",
  percentIconDisable: "/images/general_icon/percent_icon_disable.png",
  percentIconWhite: "/images/general_icon/percent_icon_white.png",
  phoneIconBlack: "/images/general_icon/phone_icon_black.png",
  phoneIconDisable: "/images/general_icon/phone_icon_disable.png",
  phoneIconWhite: "/images/general_icon/phone_icon_white.png",
  playIcon: "/images/general_icon/play-icon.png",
  plumbimgIconBlack: "/images/general_icon/plumbimg_icon_black.png",
  plumbimgIconDisable: "/images/general_icon/plumbimg_icon_disable.png",
  plumbimgIconWhite: "/images/general_icon/plumbimg_icon_white.png",
  powerIconAqua: "/images/general_icon/power_icon_aqua.png",
  powerIconBlack: "/images/general_icon/power_icon_black.png",
  powerIconDisable: "/images/general_icon/power_icon_disable.png",
  powerIconWhite: "/images/general_icon/power_icon_white.png",
  qrIconBlack: "/images/general_icon/qr_icon_black.png",
  qrIconDisable: "/images/general_icon/qr_icon_disable.png",
  qrIconWhite: "/images/general_icon/qr_icon_white.png",
  questionMarkIconBlack: "/images/general_icon/question_mark_icon_black.png",
  questionMarkIconDisable:
    "/images/general_icon/question_mark_icon_disable.png",
  questionMarkIconWhite: "/images/general_icon/question_mark_icon_white.png",
  refreshIconBlack: "/images/general_icon/refresh_icon_black.png",
  refreshIconDisable: "/images/general_icon/refresh_icon_disable.png",
  refreshIconWhite: "/images/general_icon/refresh_icon_white.png",
  refundIconBlack: "/images/general_icon/refund_icon_black.png",
  refundIconDisable: "/images/general_icon/refund_icon_disable.png",
  refundIconWhite: "/images/general_icon/refund_icon_white.png",
  rightIconBlack: "/images/general_icon/right_icon_black.png",
  rightIconDisable: "/images/general_icon/right_icon_disable.png",
  rightIconWhite: "/images/general_icon/right_icon_white.png",
  ringIconBlack: "/images/general_icon/ring_icon_black.png",
  ringIconDisable: "/images/general_icon/ring_icon_disable.png",
  ringIconWhite: "/images/general_icon/ring_icon_white.png",
  roomAvailableIcon: "/images/general_icon/room_available_icon.png",
  roomDisableIcon: "/images/general_icon/room_disable_icon.png",
  roomOccupiedIcon: "/images/general_icon/room_occupied_icon.png",
  searchIconBlack: "/images/general_icon/search_icon_black.png",
  searchIconDisable: "/images/general_icon/search_icon_disable.png",
  searchIconFillBlack: "/images/general_icon/search_icon_fill_black.png",
  searchIconFillDisable: "/images/general_icon/search_icon_fill_disable.png",
  searchIconFillWhite: "/images/general_icon/search_icon_fill_white.png",
  searchIconWhite: "/images/general_icon/search_icon_white.png",
  shareIconBlack: "/images/general_icon/share_icon_black.png",
  shareIconDisable: "/images/general_icon/share_icon_disable.png",
  shareIconWhite: "/images/general_icon/share_icon_white.png",
  signUpIconBlack: "/images/general_icon/sign_up_icon_black.png",
  signUpIconDisable: "/images/general_icon/sign_up_icon_disable.png",
  signUpIconWhite: "/images/general_icon/sign_up_icon_white.png",
  smartLockIconBlack: "/images/general_icon/smart_lock_icon_black.png",
  smartLockIconDisable: "/images/general_icon/smart_lock_icon_disable.png",
  smartLockIconWhite: "/images/general_icon/smart_lock_icon_white.png",
  spaceIconBlack: "/images/general_icon/space_icon_black.png",
  spaceIconDisable: "/images/general_icon/space_icon_disable.png",
  spaceIconWhite: "/images/general_icon/space_icon_white.png",
  squareIcon: "/images/general_icon/square_icon.png",
  stepCompletedIcon: "/images/general_icon/step_completed_icon.png",
  step1Icon: "/images/general_icon/step1_icon.png",
  step2Icon: "/images/general_icon/step2_icon.png",
  step3Icon: "/images/general_icon/step3_icon.png",
  termIconBlack: "/images/general_icon/term_icon_black.png",
  termIconDisable: "/images/general_icon/term_icon_disable.png",
  termIconWhite: "/images/general_icon/term_icon_white.png",
  tiktokIcon: "/images/general_icon/tiktok_icon.png",
  twitterIcon: "/images/general_icon/twitter_icon.png",
  upIconBlack: "/images/general_icon/up_icon_black.png",
  upIconDisable: "/images/general_icon/up_icon_disable.png",
  upIconWhite: "/images/general_icon/up_icon_white.png",
  washingMachineIconBlack:
    "/images/general_icon/washing_machine_icon_black.png",
  washingMachineIconDisable:
    "/images/general_icon/washing_machine_icon_disable.png",
  washingMachineIconWhite:
    "/images/general_icon/washing_machine_icon_white.png",
  whatsappIcon: "/images/general_icon/whatsapp_icon.png",
  whatsppIconWhite: "/images/general_icon/whatspp_icon_white.png",
  windowIconBlack: "/images/general_icon/window_icon_black.png",
  windowIconDisable: "/images/general_icon/window_icon_disable.png",
  windowIconWhite: "/images/general_icon/window_icon_white.png",
  withdrawIconBlack: "/images/general_icon/withdraw_icon_black.png",
  withdrawIconDisable: "/images/general_icon/withdraw_icon_disable.png",
  withdrawIconWhite: "/images/general_icon/withdraw_icon_white.png",
  youtubeIcon: "/images/general_icon/youtube_icon.png",
  zhIcon: "/images/general_icon/zh_icon.png",
  zoomInIcon: "/images/general_icon/zoom_in_icon.png",
  zoomOutIcon: "/images/general_icon/zoom_out_icon.png",
  uploadIconBlack: "/images/primary_icon/upload_icon_black.png",
  uploadIconDisable: "/images/primary_icon/upload_icon_disable.png",
  uploadIconWhite: "/images/primary_icon/upload_icon_white.png",
  reportIconBlack: "/images/primary_icon/report_icon_black.png",
  reportIconDisable: "/images/primary_icon/report_icon_disable.png",
  reportIconWhite: "/images/primary_icon/report_icon_white.png",
};

const images = () => {
  switch (process.env.PROJECT_NAME) {
    case "SPACIFY":
      return {
        cinemaCarIcon: "/spacify/images/primary_icon/cinema_car_icon.png",
        alertIconActive: "/spacify/images/primary_icon/alert_icon_active.png",
        appointmentIconActive:
          "/spacify/images/primary_icon/appointment_icon_active.png",
        bankIconActive: "/spacify/images/primary_icon/bank_icon_active.png",
        bathroomIconActive:
          "/spacify/images/primary_icon/bathroom_icon_active.png",
        chartIconActive: "/spacify/images/primary_icon/chart_icon_active.png",
        cinemaHouseIcon: "/spacify/images/primary_icon/cinema_house_icon.png",
        circleIconFillActive:
          "/spacify/images/primary_icon/circle_icon_fill_active.png",
        cleaningIconActive:
          "/spacify/images/primary_icon/cleaning_icon_active.png",
        coinIconActive: "/spacify/images/primary_icon/coin_icon_active.png",
        collegeIcon: "/spacify/images/primary_icon/college_icon.png",
        downIconActive: "/spacify/images/primary_icon/down_icon_active.png",
        editIconActive: "/spacify/images/primary_icon/edit_icon_active.png",
        electricalIconActive:
          "/spacify/images/primary_icon/electrical_icon_active.png",
        enquiryIconActive:
          "/spacify/images/primary_icon/enquiry_icon_active.png",
        feedbackIconActive:
          "/spacify/images/primary_icon/feedback_icon_active.png",
        femaleUnitIconActive:
          "/spacify/images/primary_icon/female_unit_icon_active.png",
        generalEnquiryIconActive:
          "/spacify/images/primary_icon/general_enquiry_icon_active.png",
        imageIconActive: "/spacify/images/primary_icon/image_icon_active.png",
        leftIconActive: "/spacify/images/primary_icon/left_icon_active.png",
        listIconActive: "/spacify/images/primary_icon/list_icon_active.png",
        locationIconActive:
          "/spacify/images/primary_icon/location_icon_active.png",
        maintenanceRequestIconActive:
          "/spacify/images/primary_icon/maintenance_request_icon_active.png",
        moreIconActive: "/spacify/images/primary_icon/more_icon_active.png",
        nearbyIcon: "/spacify/images/primary_icon/nearby_icon.png",
        outlineStartIcon: "/spacify/images/primary_icon/outline_start_icon.png",
        plumbingIconActive:
          "/spacify/images/primary_icon/plumbimg_icon_active.png",
        promotionIconWhite:
          "/spacify/images/primary_icon/promotion_icon_white.png",
        questionMarkIconActive:
          "/spacify/images/primary_icon/question_mark_icon_active.png",
        recommendIcon: "/spacify/images/primary_icon/recommend_icon.png",
        renoExpertIconActive:
          "/spacify/images/primary_icon/RenoExpert_icon_active.png",
        rightIconActive: "/spacify/images/primary_icon/right_icon_active.png",
        ringIconActive: "/spacify/images/primary_icon/ring_icon_active.png",
        upIconActive: "/spacify/images/primary_icon/up_icon_active.png",
        userIconActive: "/spacify/images/primary_icon/user_icon_active.png",
        washingMachineIconActive:
          "/spacify/images/primary_icon/washing_machine_icon_active.png",
        windowIconActive: "/spacify/images/primary_icon/window_icon_active.png",
        accountIconFillActive:
          "/spacify/images/primary_icon/accounr_icon_fill_active.png",
        accountIconActive:
          "/spacify/images/primary_icon/account_icon_active.png",
        addIconActive: "/spacify/images/primary_icon/add_icon_active.png",
        agreementIconActive:
          "/spacify/images/primary_icon/agreement_icon_active.png",
        bedIconActive: "/spacify/images/primary_icon/bed_icon_active.png",
        buildingIconActive:
          "/spacify/images/primary_icon/building_icon_active.png",
        carParkIconActive:
          "/spacify/images/primary_icon/car_park_icon_active.png",
        carParkOccupancyIconActive:
          "/spacify/images/primary_icon/car_park_occupancy_icon_active.png",
        chatIconActive: "/spacify/images/primary_icon/chat_icon_active.png",
        checkIconActive: "/spacify/images/primary_icon/check_icon_active.png",
        closeIconActive: "/spacify/images/primary_icon/close_icon_active.png",
        downloadIconActive:
          "/spacify/images/primary_icon/download_icon_active.png",
        emailIconActive: "/spacify/images/primary_icon/email_icon_active.png",
        expensesIconActive:
          "/spacify/images/primary_icon/expenses_icon_active.png",
        filterIconActive: "/spacify/images/primary_icon/filter_icon_active.png",
        helpCenterIconActive:
          "/spacify/images/primary_icon/help_center_icon_active.png",
        homeIconActive: "/spacify/images/primary_icon/home_icon_active.png",
        homeIconFillActive:
          "/spacify/images/primary_icon/home_icon_fill_active.png",
        incomeIconActive: "/spacify/images/primary_icon/income_icon_active.png",
        infoIconActive: "/spacify/images/primary_icon/info_icon_active.png",
        invoiceIconActive:
          "/spacify/images/primary_icon/invoice_icon_active.png",
        lockIconActive: "/spacify/images/primary_icon/lock_icon_active.png",
        meterIconActive: "/spacify/images/primary_icon/meter_icon_active.png",
        occupancyIconActive:
          "/spacify/images/primary_icon/occupancy_icon_active.png",
        percentIconActive:
          "/spacify/images/primary_icon/percent_icon_active.png",
        phoneIconActive: "/spacify/images/primary_icon/phone_icon_active.png",
        powerIconActive: "/spacify/images/primary_icon/power_icon_active.png",
        qrIconActive: "/spacify/images/primary_icon/qr_icon_active.png",
        refreshIconActive:
          "/spacify/images/primary_icon/refresh_icon_active.png",
        refundIconActive: "/spacify/images/primary_icon/refund_icon_active.png",
        searchIconActive: "/spacify/images/primary_icon/search_icon_active.png",
        searchIconFillActive:
          "/spacify/images/primary_icon/search_icon_fill_active.png",
        shareIconActive: "/spacify/images/primary_icon/share_icon_active.png",
        signUpIconActive:
          "/spacify/images/primary_icon/sign_up_icon_active.png",
        smartLockIconActive:
          "/spacify/images/primary_icon/smart_lock_icon_active.png",
        spaceIconActive: "/spacify/images/primary_icon/space_icon_active.png",
        termIconActive: "/spacify/images/primary_icon/term_icon_active.png",
        withdrawIconActive:
          "/spacify/images/primary_icon/withdraw_icon_active.png",
        uploadIconActive: "/spacify/images/primary_icon/upload_icon_active.png",
        reportIconActive: "/spacify/images/primary_icon/report_icon_active.png",
        emptyBox: "/spacify/images/emptyBox.png",
        icBackSample: "/spacify/images/ic_back_sample.png",
        icFrontSample: "/spacify/images/ic_front_sample.png",
        logo: "/spacify/images/logo.webp",
        logoBlackWithText: "/spacify/images/logo_black_with_text.png",
        logoHorizontalColor: "/spacify/images/logo_horizontal_color.webp",
        ownerCard: "/spacify/images/owner_card.png",
        tenantCard: "/spacify/images/tenant_card.png",
        imageNotFound: "/spacify/images/logo.webp",
        pageNotFound: "/spacify/images/404_image.png",
      };
    case "COZYHOMES":
      return {
        cinemaCarIcon: "/cozyHomes/images/primary_icon/cinema_car_icon.png",
        alertIconActive: "/cozyHomes/images/primary_icon/alert_icon_active.png",
        appointmentIconActive:
            "/cozyHomes/images/primary_icon/appointment_icon_active.png",
        bankIconActive: "/cozyHomes/images/primary_icon/bank_icon_active.png",
        bathroomIconActive:
            "/cozyHomes/images/primary_icon/bathroom_icon_active.png",
        chartIconActive: "/cozyHomes/images/primary_icon/chart_icon_active.png",
        cinemaHouseIcon: "/cozyHomes/images/primary_icon/cinema_house_icon.png",
        circleIconFillActive:
            "/cozyHomes/images/primary_icon/circle_icon_fill_active.png",
        cleaningIconActive:
            "/cozyHomes/images/primary_icon/cleaning_icon_active.png",
        coinIconActive: "/cozyHomes/images/primary_icon/coin_icon_active.png",
        collegeIcon: "/cozyHomes/images/primary_icon/college_icon.png",
        downIconActive: "/cozyHomes/images/primary_icon/down_icon_active.png",
        editIconActive: "/cozyHomes/images/primary_icon/edit_icon_active.png",
        electricalIconActive:
            "/cozyHomes/images/primary_icon/electrical_icon_active.png",
        enquiryIconActive:
            "/cozyHomes/images/primary_icon/enquiry_icon_active.png",
        feedbackIconActive:
            "/cozyHomes/images/primary_icon/feedback_icon_active.png",
        femaleUnitIconActive:
            "/cozyHomes/images/primary_icon/female_unit_icon_active.png",
        generalEnquiryIconActive:
            "/cozyHomes/images/primary_icon/general_enquiry_icon_active.png",
        imageIconActive: "/cozyHomes/images/primary_icon/image_icon_active.png",
        leftIconActive: "/cozyHomes/images/primary_icon/left_icon_active.png",
        listIconActive: "/cozyHomes/images/primary_icon/list_icon_active.png",
        locationIconActive:
            "/cozyHomes/images/primary_icon/location_icon_active.png",
        maintenanceRequestIconActive:
            "/cozyHomes/images/primary_icon/maintenance_request_icon_active.png",
        moreIconActive: "/cozyHomes/images/primary_icon/more_icon_active.png",
        nearbyIcon: "/cozyHomes/images/primary_icon/nearby_icon.png",
        outlineStartIcon: "/cozyHomes/images/primary_icon/outline_start_icon.png",
        plumbingIconActive:
            "/cozyHomes/images/primary_icon/plumbimg_icon_active.png",
        promotionIconWhite:
            "/cozyHomes/images/primary_icon/promotion_icon_white.png",
        questionMarkIconActive:
            "/cozyHomes/images/primary_icon/question_mark_icon_active.png",
        recommendIcon: "/cozyHomes/images/primary_icon/recommend_icon.png",
        renoExpertIconActive:
            "/cozyHomes/images/primary_icon/RenoExpert_icon_active.png",
        rightIconActive: "/cozyHomes/images/primary_icon/right_icon_active.png",
        ringIconActive: "/cozyHomes/images/primary_icon/ring_icon_active.png",
        upIconActive: "/cozyHomes/images/primary_icon/up_icon_active.png",
        userIconActive: "/cozyHomes/images/primary_icon/user_icon_active.png",
        washingMachineIconActive:
            "/cozyHomes/images/primary_icon/washing_machine_icon_active.png",
        windowIconActive: "/cozyHomes/images/primary_icon/window_icon_active.png",
        accountIconFillActive:
            "/cozyHomes/images/primary_icon/accounr_icon_fill_active.png",
        accountIconActive:
            "/cozyHomes/images/primary_icon/account_icon_active.png",
        addIconActive: "/cozyHomes/images/primary_icon/add_icon_active.png",
        agreementIconActive:
            "/cozyHomes/images/primary_icon/agreement_icon_active.png",
        bedIconActive: "/cozyHomes/images/primary_icon/bed_icon_active.png",
        buildingIconActive:
            "/cozyHomes/images/primary_icon/building_icon_active.png",
        carParkIconActive:
            "/cozyHomes/images/primary_icon/car_park_icon_active.png",
        carParkOccupancyIconActive:
            "/cozyHomes/images/primary_icon/car_park_occupancy_icon_active.png",
        chatIconActive: "/cozyHomes/images/primary_icon/chat_icon_active.png",
        checkIconActive: "/cozyHomes/images/primary_icon/check_icon_active.png",
        closeIconActive: "/cozyHomes/images/primary_icon/close_icon_active.png",
        downloadIconActive:
            "/cozyHomes/images/primary_icon/download_icon_active.png",
        emailIconActive: "/cozyHomes/images/primary_icon/email_icon_active.png",
        expensesIconActive:
            "/cozyHomes/images/primary_icon/expenses_icon_active.png",
        filterIconActive: "/cozyHomes/images/primary_icon/filter_icon_active.png",
        helpCenterIconActive:
            "/cozyHomes/images/primary_icon/help_center_icon_active.png",
        homeIconActive: "/cozyHomes/images/primary_icon/home_icon_active.png",
        homeIconFillActive:
            "/cozyHomes/images/primary_icon/home_icon_fill_active.png",
        incomeIconActive: "/cozyHomes/images/primary_icon/income_icon_active.png",
        infoIconActive: "/cozyHomes/images/primary_icon/info_icon_active.png",
        invoiceIconActive:
            "/cozyHomes/images/primary_icon/invoice_icon_active.png",
        lockIconActive: "/cozyHomes/images/primary_icon/lock_icon_active.png",
        meterIconActive: "/cozyHomes/images/primary_icon/meter_icon_active.png",
        occupancyIconActive:
            "/cozyHomes/images/primary_icon/occupancy_icon_active.png",
        percentIconActive:
            "/cozyHomes/images/primary_icon/percent_icon_active.png",
        phoneIconActive: "/cozyHomes/images/primary_icon/phone_icon_active.png",
        powerIconActive: "/cozyHomes/images/primary_icon/power_icon_active.png",
        qrIconActive: "/cozyHomes/images/primary_icon/qr_icon_active.png",
        refreshIconActive:
            "/cozyHomes/images/primary_icon/refresh_icon_active.png",
        refundIconActive: "/cozyHomes/images/primary_icon/refund_icon_active.png",
        searchIconActive: "/cozyHomes/images/primary_icon/search_icon_active.png",
        searchIconFillActive:
            "/cozyHomes/images/primary_icon/search_icon_fill_active.png",
        shareIconActive: "/cozyHomes/images/primary_icon/share_icon_active.png",
        signUpIconActive:
            "/cozyHomes/images/primary_icon/sign_up_icon_active.png",
        smartLockIconActive:
            "/cozyHomes/images/primary_icon/smart_lock_icon_active.png",
        spaceIconActive: "/cozyHomes/images/primary_icon/space_icon_active.png",
        termIconActive: "/cozyHomes/images/primary_icon/term_icon_active.png",
        withdrawIconActive:
            "/cozyHomes/images/primary_icon/withdraw_icon_active.png",
        uploadIconActive: "/cozyHomes/images/primary_icon/upload_icon_active.png",
        reportIconActive: "/cozyHomes/images/primary_icon/report_icon_active.png",
        emptyBox: "/cozyHomes/images/emptyBox.png",
        icBackSample: "/cozyHomes/images/ic_back_sample.png",
        icFrontSample: "/cozyHomes/images/ic_front_sample.png",
        logo: "/cozyHomes/images/logo.webp",
        logoBlackWithText: "/cozyHomes/images/logo_black_with_text.png",
        logoHorizontalColor: "/cozyHomes/images/logo_horizontal_color.webp",
        ownerCard: "/cozyHomes/images/owner_card.png",
        tenantCard: "/cozyHomes/images/tenant_card.png",
        imageNotFound: "/cozyHomes/images/logo.webp",
        pageNotFound: "/cozyHomes/images/404_image.png",
      };
  }
};

export default { ...images(), ...GeneralImage };
